CC	= gcc -Wall
CFLAGS	= -g -c -O2 -I/usr/X11R6/include -I../include
LFLAGS	= -g -L/usr/X11R6/lib -lX11 -lXext -lxpg4

.c.o:
	$(CC) $(CFLAGS) $<

OBJS =	main.o graphics.o image8.o image16.o image24.o image32.o \
	audio.o dungeon.o goods.o user.o message.o status.o \
	context.o field.o tower.o battle.o boss.o cave.o \
	equip.o inventory.o shop.o user_dead.o use_item.o \
	animation.o menu.o pause.o opening.o ending.o \
	numinous.o user_io.o fade.o

SRCS =	x11/main.c graphics.c image8.c image16.c image24.c image32.c \
	audio.c dungeon.c goods.c user.c message.c status.c \
	context.c field.c tower.c battle.c boss.c cave.c \
	equip.c inventory.c shop.c user_dead.c use_item.c \
	animation.c menu.c pause.c opening.c ending.c \
	numinous.c user_io.c fade.c

all: xanadu waveplay

main.o: x11/main.c

xanadu: $(OBJS)
	$(CC) $(LFLAGS) -o $@ $(OBJS)

waveplay: x11/waveplay.c
	$(CC) -g -o $@ x11/waveplay.c

depend:
	mkdep $(CFLAGS) $(SRCS)

clean:
	rm -f *~ *.o *.core
