.autodepend
.cacheautodepend
#.SUFFIXES: .obj .rc .res .exe

CC	= bcc32
LINK	= tlink32
RCC	= brcc32

#CFLAGS	= -v -c -tWE -I../include
#LFLAGS	= -v -x -aa -Tpe

CFLAGS	= -5 -O2 -OS -c -tWE -I../include
LFLAGS	= -x -aa -Tpe

.c.obj:
	$(CC) $(CFLAGS) $<

.rc.res:
	$(RCC) $<

OBJS1	= main.obj graphics.obj image8.obj image16.obj image24.obj image32.obj
OBJS2	= audio.obj dungeon.obj goods.obj user.obj message.obj status.obj 
OBJS3	= context.obj field.obj tower.obj battle.obj boss.obj cave.obj
OBJS4	= equip.obj inventory.obj shop.obj user_dead.obj use_item.obj
OBJS5	= animation.obj menu.obj pause.obj opening.obj ending.obj
OBJS6	= numinous.obj user_io.obj fade.obj

OBJS	= $(OBJS1) $(OBJS2) $(OBJS3) $(OBJS4) $(OBJS5) $(OBJS6)

STARTUP	= c0w32.obj
LIBS	= cw32mt.lib import32.lib
RES	= xanadu.res
TARGET	= xanadu.exe midiplay.exe waveplay.exe

all: $(TARGET)

xanadu.exe: $(OBJS) $(RES) xanadu.rsp
	$(LINK) @xanadu.rsp

xanadu.rsp: Makefile
	echo $(LFLAGS)+ > $@
	echo $(STARTUP) $(OBJS1)+ >> $@
	echo $(OBJS2)+ >> $@
	echo $(OBJS3)+ >> $@
	echo $(OBJS4)+ >> $@
	echo $(OBJS5)+ >> $@
	echo $(OBJS6)+ >> $@
	echo ,xanadu.exe,, $(LIBS),,$(RES) >> $@

graphics.obj: graphics.c
	$(CC) -O2 $(CFLAGS) graphics.c

midiplay.exe: midiplay.c
	$(CC) -5 -O2 midiplay.c import32.lib

waveplay.exe: waveplay.c
	$(CC) -5 -O2 waveplay.c import32.lib

clean:
	rm -f *~ *.obj *.map *.RES *.TR2
	rm -f ../include/*~

rebuild:
	rm $(TARGET)
	make clean
	make all

ARCHIVE_DIR = d:/home/archive

xanadu.lzh: $(TARGET)
	make xa_bin.lzh
	make clean
	cd ..\..
	mkdir -p $(ARCHIVE_DIR)
	rm -f $(ARCHIVE_DIR)/xanadu.lzh
	lha32 a -d1 $(ARCHIVE_DIR)/xanadu.lzh xanadu/
	lha32 d $(ARCHIVE_DIR)/xanadu.lzh xaii*.mid xa2*.mid *.WAV
	cp $(ARCHIVE_DIR)/xanadu.lzh $(ARCHIVE_DIR)/xa_lite.lzh
	lha32 d $(ARCHIVE_DIR)/xa_lite.lzh *.bmp

xa_bin.lzh: xanadu.exe
	mkdir -p $(ARCHIVE_DIR)
	lha32 a $(ARCHIVE_DIR)/xa_bin.lzh xanadu.exe

xanadu.tar.gz: $(TARGET)
	make clean
	cd ..\..
	mkdir -p $(ARCHIVE_DIR)
	rm -f $(ARCHIVE_DIR)/xanadu.tar.gz $(ARCHIVE_DIR)/xanadu.exe.gz
	tar cvf - -C xanadu . > $(ARCHIVE_DIR)/xanadu.tar
	gzip $(ARCHIVE_DIR)/xanadu.tar
