CC	= gcc -mno-cygwin
CFLAGS	= -c -O2 -I../include -D__WIN32__
LFLAGS	= -L/lib

.c.o:
	$(CC) $(CFLAGS) $<

OBJS=	main.o graphics.o image8.o image16.o image24.o image32.o \
	audio.o dungeon.o goods.o user.o message.o status.o  \
	context.o field.o tower.o battle.o boss.o cave.o \
	equip.o inventory.o shop.o user_dead.o use_item.o \
	animation.o menu.o pause.o opening.o ending.o \
	numinous.o user_io.o fade.o

all: xanadu.exe midiplay.exe waveplay.exe

xanadu.exe: $(OBJS)
	$(CC) $(LFLAGS) -o $@ $(OBJS) -lmingw32 -lgdi32

midiplay.exe: midiplay.o
	$(CC) $(LFLAGS) -o $@ midiplay.o -lwinmm

waveplay.exe: waveplay.o
	$(CC) $(LFLAGS) -o $@ waveplay.o -lwinmm

depend:
	mkdep $(CFLAGS) $(SRCS)

clean:
	rm -f *~ *.o *.core
